name: .NET CI / Docker Publish

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore all dependencies
        run: dotnet restore "Hotel_Booking_API/Hotel_Booking.sln"

      - name: Build solution
        run: dotnet build "Hotel_Booking_API/Hotel_Booking.sln" --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test "tests/Hotel_Booking.UnitTests/Hotel_Booking.UnitTests.csproj" --configuration Release

      - name: Run Integration Tests (SQLite In-Memory)
        env:
          ASPNETCORE_ENVIRONMENT: Test
        run: dotnet test "tests/Hotel_Booking.IntegrationTests/Hotel_Booking.IntegrationTests.csproj" --configuration Release --settings tests/Hotel_Booking.IntegrationTests/test.runsettings

      - name: Publish
        run: dotnet publish "Hotel_Booking_API/Hotel_Booking_API.csproj" -c Release -o out

      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hotel-booking-api
          path: out

  docker_publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg JwtSettings__SecretKey="${{ secrets.JwtSettings__SecretKey }}" \
            --build-arg Stripe__ApiKey="${{ secrets.Stripe__ApiKey }}" \
            --build-arg Stripe__PublishableKey="${{ secrets.Stripe__PublishableKey }}" \
            --build-arg Stripe__WebhookSecret="${{ secrets.Stripe__WebhookSecret }}" \
            --build-arg SmtpSettings__Username="${{ secrets.SmtpSettings__Username }}" \
            --build-arg SmtpSettings__Password="${{ secrets.SmtpSettings__Password }}" \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hotel-booking-api:latest \
            ./Hotel_Booking_API

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hotel-booking-api:latest
